#!/bin/bash

# Loan Approval Prediction - Quick Start Guide

echo "🏦 LOAN APPROVAL PREDICTION SYSTEM"
echo "=================================="
echo ""
echo "Your interactive loan approval prediction system is ready!"
echo ""
echo "📋 USAGE OPTIONS:"
echo ""
echo "1️⃣  FULL ANALYSIS + INTERACTIVE PREDICTIONS"
echo "   python main.py"
echo "   • Complete dataset analysis (5,000 samples)"
echo "   • Bias detection and statistical analysis"  
echo "   • ML model training with 60/20/20 split"
echo "   • Interactive prediction mode"
echo ""
echo "2️⃣  QUICK STANDALONE PREDICTIONS"
echo "   python predict_loan.py"
echo "   • Fast model training (3,000 samples)"
echo "   • Direct to interactive predictions"
echo ""
echo "3️⃣  TEST THE SYSTEM"
echo "   python test_prediction.py"
echo "   • Automated test with sample cases"
echo "   • See how different profiles are evaluated"
echo ""
echo "📝 WHAT YOU'LL ENTER:"
echo "   • Demographics: Gender, Race, Education, Age"
echo "   • Financial: Income, Credit Score, Loan Amount"
echo "   • Property: Value, Down Payment, Debt-to-Income"
echo ""
echo "📊 WHAT YOU'LL GET:"
echo "   • ✅/❌ Approval Decision"
echo "   • Probability percentage (0-100%)"
echo "   • 🟢🟡🟠🔴 Risk Assessment"
echo "   • Personalized recommendations"
echo ""
echo "⚠️  EDUCATIONAL PURPOSE:"
echo "   This tool demonstrates bias patterns in ML lending models"
echo "   and shows how race, gender, and other factors can affect"
echo "   loan approval decisions."
echo ""
echo "🚀 TRY IT NOW:"
echo "   Choose one of the options above and start predicting!"
echo ""
